### PR TITLE
do not turn filename.xwd into filename.png.png

### PR DESCRIPTION
**Pull request by sgerwk**
If the input file has an extension, both .ext and $ match the regular expression. Both get replaced by .png, resulting in filename.png.png

### CODE REVIEW

**Comment by drj11** [comment]
Great, but please fix one problem at a time.

**Comment by drj11** [comment]
Thanks for investigating this. I have merged the a572bd8 commit.

**Comment by drj11** [comment]
Just to let you know that I've renamed the default branch from `master` to `main`.

**Comment by drj11** [comment]
I have also fixed (i think) the bug implied by your https://github.com/drj11/xwd2png/pull/2/commits/14f2489b63d6444c6a9cee7d30ae15e923c1a17c commit.

**Comment by sgerwk** [comment]
> I have also fixed (i think) the bug implied by your [14f2489](https://github.com/drj11/xwd2png/commit/14f2489b63d6444c6a9cee7d30ae15e923c1a17c) commit.

Yes, it fixes it. Thanks.

**Pull request closed without merging**
